from pyperclip import *
def fix(a):
    e = a
    e = e.replace( ' 버수 ' , "쾅").replace( ' died ' ,"쾅").replace( ' :keyboard: ' ,"쾅").replace( ' · – – 　– 　– – · 　· · · · ' , "쾅")
    e = e.replace( ' 숩어 ' ,"왘").replace( ' 옼 ' ,"쾅").replace( ' dkhz ' , "쾅").replace( ' obabrebrus ' ,"쾅").replace( ' 컴퓨터실 ' , "왘")
    e = e.replace( ' sad ' , "왘").replace( ' 수버핑 ' , "왘").replace( ' 수버역할핑 ' ,"왘").replace( ' ␚ ' , "왘")#.replace( ' 숩숩 ' , "왘")
    e = e.replace( ' :died: ' ,"쾅").replace( ' 내부 헤에로 과부하! ' ,"왘").replace( ' #수버-주기는-방 ' , "왘").replace( ' 스윽술버스윽 ' ,  ' 쾅쾅쾅 ' )
    e = e.replace( ' :surber: ' ,"왘").replace( ' :sad: ' ,"왘").replace( ' 수버 ' , "왘").replace( ' ⠘⠎⠠⠍ ' , "쾅")
    e = e.replace( ' 내부 헤에로 과부하 ' , "왘").replace( ' surber ' ,"왘").replace( ' deid ' ,"왘")
    e = e.replace( ' 헤에헤에 ' ,  ' 쾅쾅 ' ).replace( ' 에헤에헤 ' , ' 왘왘 ' ).replace( ' babo ' , "왘").replace( ' 버스 ' , "쾅")
    e = e.replace( ' 하부과 ' ,"쾅").replace( ' jqnt ' , "쾅").replace( ' 숩버 ' , "왘").replace( ' ––·　····　·––　– ' ,"왘")
    e = e.replace( ' rebrus ' , "쾅").replace( ' 헤에 ' ,"왘").replace( ' tnqj ' , "왘").replace( ' ꓤꓱꓭꓤꓵꓢ ' ,"쾅")
    e = e.replace( ' 녀귣ㄱ ' , "왘").replace( ' 숩 ' ,"왘").replace( ' rotinom ' ,"쾅").replace( ' ––·　····　·––　– ' , "왘")
    e = e.replace( ' ㄱ듀견 ' ,"쾅").replace( ' 모니터 ' , "왘").replace( ' 터니모 ' ,"쾅").replace( ' :mouse_three_button: ' , "쾅")
    e = e.replace( ' SurberHD_ ' , "왘").replace( ' ｒｅｂｒｕＳ ' , "쾅").replace( ' JnL ' ,"쾅")
    e = e.replace( ' SurberHD ' , "왘").replace( ' :computer: ' , "왘").replace( ' 술버 ' ,"왘").replace( ' ⓢⓤⓡⓑⓔⓡ ' , "왘")
    e = e.replace( ' suber ' ,"쾅").replace( ' ㅓ붓 ' , "쾅").replace( ' 스윽 ' ,"왘").replace( ' monitor ' , "왘")
    e = e.replace( ' 에헤 ' , "쾅").replace( ' 녀ㅠㄷㄱ ' ,"쾅").replace( ' Ｓｕｒｂｅｒ ' ,"왘")
    e = e.replace( ' ㅣㅏ ' ,"쾅").replace( ' 얃ㅇ ' , "쾅").replace( ' genius ' , "쾅").replace( ' – – · 　· · · · 　· – – 　– ' , "왘")
    e = e.replace( ' 천재 ' , "쾅").replace( ' ㅔ ' , "왘").replace( ' 슥 ' ,"왘").replace( ' 터퓨컴 ' , "왘")
    e = e.replace( ' -수- ' , "왘").replace( ' 바부 ' , "왘").replace( ' 긋 ' ,"쾅").replace( ' ㅇ댱 ' , "왘")
    e = e.replace( ' ㄴㅁㅇ ' , "왘").replace( ' 밥부 ' , "왘").replace( ' 과부하 ' , "왘")
    e = e.replace( ' das ' , "쾅").replace( ' knalb ' , "쾅").replace( ' 버스 ' , "쾅").replace( ' ⓡⓔⓑⓡⓤⓢ ' ,"쾅")
    e = e.replace( ' :desktop: ' ,"왘").replace( ' obab ' , "쾅").replace( ' #h ' , "쾅").replace( ' :regional_indicator_r: :regional_indicator_e: :regional_indicator_b: :regional_indicator_r: :regional_indicator_u: nal_indicatodicator_s:desktop:dieop:died: ' , ' 왘쾅왘 ' )
    e = e.replace( ' potksed ' ,"쾅").replace( ' zhkd ' ,"왘").replace( ' blank ' , "왘")
    e = e.replace( ' ㅇㅁㄴ ' , "쾅").replace( ' 🇷 🇪 🇧 🇷 🇺 🇸 ' , "쾅")
    e = e.replace( ' :regional_indicator_s: :regional_indicator_u: :regional_indicator_r: :regional_indicator_b: :regional_indicator_e: :regional_indicator_r: ' , "왘")
    e = e.replace( ' desktop ' , "왘").replace( ' 드보키 ' ,"왘").replace( ' rebus ' , "왘")
    e = e.replace( ' !rank ' ,"왘").replace( ' 재천 ' ,"왘").replace( ' 키보드 ' , "쾅")
    e = e.replace( ' 콩 ' , "왘").replace( ' 마우스 ' , "쾅").replace( ' 컴퓨터 ' , "쾅")
    e = e.replace( ' 윽스 ' , "쾅").replace( ' 스우마 ' , "왘").replace( ' ⠠⠍⠘⠎ ' ,"왘")
    e = e.replace('버수', '왘').replace('died','왘').replace(':keyboard:','왘').replace('· – – 　– 　– – · 　· · · ·', '왘')
    e = e.replace('숩어','쾅').replace('옼','왘').replace('dkhz', '왘').replace('obabrebrus','왘').replace('컴퓨터실', '쾅')
    e = e.replace('sad', '쾅').replace('수버핑', '쾅').replace('수버역할핑','쾅').replace('␚', '쾅')#.replace('숩숩', '쾅')
    e = e.replace(':died:','왘').replace('내부 헤에로 과부하!','쾅').replace('#수버-주기는-방', '쾅').replace('스윽술버스윽', '쾅쾅쾅')
    e = e.replace(':surber:','쾅').replace(':sad:','쾅').replace("수버", '쾅').replace('⠘⠎⠠⠍', '왘')
    e = e.replace('내부 헤에로 과부하', '쾅').replace('surber','쾅').replace('deid','쾅')
    e = e.replace('헤에헤에', '쾅쾅').replace('에헤에헤','왘왘').replace('babo', '쾅').replace('버스', '왘')
    e = e.replace('하부과','왘').replace('jqnt', '왘').replace('숩버', '쾅').replace('––·　····　·––　–','쾅')
    e = e.replace('rebrus', '왘').replace('헤에','쾅').replace('tnqj', '쾅').replace('ꓤꓱꓭꓤꓵꓢ','왘')
    e = e.replace('녀귣ㄱ', '쾅').replace('숩','쾅').replace('rotinom','왘').replace('––·　····　·––　–', '쾅')
    e = e.replace('ㄱ듀견','왘').replace('모니터', "쾅").replace('터니모','왘').replace(':mouse_three_button:', '왘')
    e = e.replace('SurberHD_', '쾅').replace('ｒｅｂｒｕＳ', '왘').replace('JnL','왘')
    e = e.replace('SurberHD', '쾅').replace(':computer:', '쾅').replace('술버','쾅').replace('ⓢⓤⓡⓑⓔⓡ', '쾅')
    e = e.replace('suber','왘').replace('ㅓ붓', '왘').replace('스윽','쾅').replace('monitor', '쾅')
    e = e.replace('에헤', '왘').replace('녀ㅠㄷㄱ','왘').replace('Ｓｕｒｂｅｒ','쾅')
    e = e.replace('ㅣㅏ','왘').replace('얃ㅇ', '왘').replace('genius', '왘').replace('– – · 　· · · · 　· – – 　–', '쾅')
    e = e.replace('천재', '왘').replace('ㅔ', '쾅').replace('슥','쾅').replace('터퓨컴', '쾅')
    e = e.replace('-수-', '쾅').replace('바부', '쾅').replace('긋','왘').replace('ㅇ댱', '쾅')
    e = e.replace('ㄴㅁㅇ', '쾅').replace('밥부', '쾅').replace('과부하', '쾅')
    e = e.replace('das', '왘').replace('knalb', '왘').replace('버스', '왘').replace('ⓡⓔⓑⓡⓤⓢ','왘')
    e = e.replace(':desktop:','쾅').replace('obab', '왘').replace('#h', '왘').replace(':regional_indicator_r: :regional_indicator_e: :regional_indicator_b: :regional_indicator_r: :regional_indicator_u: :regional_indicator_s:desktop:died:','왘쾅왘')
    e = e.replace('potksed','왘').replace('zhkd','쾅').replace('blank', '쾅')
    e = e.replace("ㅇㅁㄴ", '왘').replace(':regional_indicator_r: :regional_indicator_e: :regional_indicator_b: :regional_indicator_r: :regional_indicator_u: :regional_indicator_s:', '왘')
    e = e.replace(':regional_indicator_s: :regional_indicator_u: :regional_indicator_r: :regional_indicator_b: :regional_indicator_e: :regional_indicator_r:', '쾅')
    e = e.replace('desktop', '쾅').replace('드보키','쾅').replace('rebus', '쾅')
    e = e.replace('!rank','쾅').replace('재천','쾅').replace('키보드', '왘')
    e = e.replace('콩', '쾅').replace('마우스', '왘').replace('컴퓨터', '왘')
    e = e.replace('윽스', '왘').replace('스우마', '쾅').replace('⠠⠍⠘⠎','쾅')

    e = e.replace(' ', '').replace(":", "").replace('!', '')
    e = e.replace('thonking~1',':thrinking~1:')
    return(e)
while True:
    a = input(' ')
    print(fix(a))
    copy(fix(a))
    
